# Database configuration
# URL for embedded HSQLDB (file-based)
db.url = jdbc:hsqldb:file:./data/vrsdb;shutdown=true

# Default HSQLDB user and password
# (default user is SA, password blank)
db.user = SA
db.password =
# Server configuration
app.server.port = 9090
app.server.core.pool.size = 8
app.server.max.pool.size = 16
app.server.keep.alive = 60
app.server.queue.size = 50